// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	postgres "github.com/arsykor/gophkeeper/internal/server/storage/postgres"
	mock "github.com/stretchr/testify/mock"
)

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: login, passwordHash
func (_m *MockUserRepository) CreateUser(login string, passwordHash string) (string, error) {
	ret := _m.Called(login, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(login, passwordHash)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(login, passwordHash)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(login, passwordHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserRepository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - login string
//   - passwordHash string
func (_e *MockUserRepository_Expecter) CreateUser(login interface{}, passwordHash interface{}) *MockUserRepository_CreateUser_Call {
	return &MockUserRepository_CreateUser_Call{Call: _e.mock.On("CreateUser", login, passwordHash)}
}

func (_c *MockUserRepository_CreateUser_Call) Run(run func(login string, passwordHash string)) *MockUserRepository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepository_CreateUser_Call) Return(_a0 string, _a1 error) *MockUserRepository_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_CreateUser_Call) RunAndReturn(run func(string, string) (string, error)) *MockUserRepository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByLogin provides a mock function with given fields: login
func (_m *MockUserRepository) GetUserByLogin(login string) (*postgres.User, error) {
	ret := _m.Called(login)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByLogin")
	}

	var r0 *postgres.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*postgres.User, error)); ok {
		return rf(login)
	}
	if rf, ok := ret.Get(0).(func(string) *postgres.User); ok {
		r0 = rf(login)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*postgres.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(login)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_GetUserByLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByLogin'
type MockUserRepository_GetUserByLogin_Call struct {
	*mock.Call
}

// GetUserByLogin is a helper method to define mock.On call
//   - login string
func (_e *MockUserRepository_Expecter) GetUserByLogin(login interface{}) *MockUserRepository_GetUserByLogin_Call {
	return &MockUserRepository_GetUserByLogin_Call{Call: _e.mock.On("GetUserByLogin", login)}
}

func (_c *MockUserRepository_GetUserByLogin_Call) Run(run func(login string)) *MockUserRepository_GetUserByLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockUserRepository_GetUserByLogin_Call) Return(_a0 *postgres.User, _a1 error) *MockUserRepository_GetUserByLogin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_GetUserByLogin_Call) RunAndReturn(run func(string) (*postgres.User, error)) *MockUserRepository_GetUserByLogin_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
