// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	postgres "github.com/arsykor/gophkeeper/internal/server/storage/postgres"
	mock "github.com/stretchr/testify/mock"
)

// MockSecretRepository is an autogenerated mock type for the SecretRepository type
type MockSecretRepository struct {
	mock.Mock
}

type MockSecretRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSecretRepository) EXPECT() *MockSecretRepository_Expecter {
	return &MockSecretRepository_Expecter{mock: &_m.Mock}
}

// CreateBinarySecret provides a mock function with given fields: s
func (_m *MockSecretRepository) CreateBinarySecret(s *postgres.Secret) (*postgres.Secret, error) {
	ret := _m.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for CreateBinarySecret")
	}

	var r0 *postgres.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(*postgres.Secret) (*postgres.Secret, error)); ok {
		return rf(s)
	}
	if rf, ok := ret.Get(0).(func(*postgres.Secret) *postgres.Secret); ok {
		r0 = rf(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*postgres.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(*postgres.Secret) error); ok {
		r1 = rf(s)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretRepository_CreateBinarySecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBinarySecret'
type MockSecretRepository_CreateBinarySecret_Call struct {
	*mock.Call
}

// CreateBinarySecret is a helper method to define mock.On call
//   - s *postgres.Secret
func (_e *MockSecretRepository_Expecter) CreateBinarySecret(s interface{}) *MockSecretRepository_CreateBinarySecret_Call {
	return &MockSecretRepository_CreateBinarySecret_Call{Call: _e.mock.On("CreateBinarySecret", s)}
}

func (_c *MockSecretRepository_CreateBinarySecret_Call) Run(run func(s *postgres.Secret)) *MockSecretRepository_CreateBinarySecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*postgres.Secret))
	})
	return _c
}

func (_c *MockSecretRepository_CreateBinarySecret_Call) Return(_a0 *postgres.Secret, _a1 error) *MockSecretRepository_CreateBinarySecret_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretRepository_CreateBinarySecret_Call) RunAndReturn(run func(*postgres.Secret) (*postgres.Secret, error)) *MockSecretRepository_CreateBinarySecret_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSecret provides a mock function with given fields: s
func (_m *MockSecretRepository) CreateSecret(s *postgres.Secret) (*postgres.Secret, error) {
	ret := _m.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for CreateSecret")
	}

	var r0 *postgres.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(*postgres.Secret) (*postgres.Secret, error)); ok {
		return rf(s)
	}
	if rf, ok := ret.Get(0).(func(*postgres.Secret) *postgres.Secret); ok {
		r0 = rf(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*postgres.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(*postgres.Secret) error); ok {
		r1 = rf(s)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretRepository_CreateSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSecret'
type MockSecretRepository_CreateSecret_Call struct {
	*mock.Call
}

// CreateSecret is a helper method to define mock.On call
//   - s *postgres.Secret
func (_e *MockSecretRepository_Expecter) CreateSecret(s interface{}) *MockSecretRepository_CreateSecret_Call {
	return &MockSecretRepository_CreateSecret_Call{Call: _e.mock.On("CreateSecret", s)}
}

func (_c *MockSecretRepository_CreateSecret_Call) Run(run func(s *postgres.Secret)) *MockSecretRepository_CreateSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*postgres.Secret))
	})
	return _c
}

func (_c *MockSecretRepository_CreateSecret_Call) Return(_a0 *postgres.Secret, _a1 error) *MockSecretRepository_CreateSecret_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretRepository_CreateSecret_Call) RunAndReturn(run func(*postgres.Secret) (*postgres.Secret, error)) *MockSecretRepository_CreateSecret_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSecret provides a mock function with given fields: id, userID
func (_m *MockSecretRepository) DeleteSecret(id string, userID string) error {
	ret := _m.Called(id, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSecret")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(id, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSecretRepository_DeleteSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSecret'
type MockSecretRepository_DeleteSecret_Call struct {
	*mock.Call
}

// DeleteSecret is a helper method to define mock.On call
//   - id string
//   - userID string
func (_e *MockSecretRepository_Expecter) DeleteSecret(id interface{}, userID interface{}) *MockSecretRepository_DeleteSecret_Call {
	return &MockSecretRepository_DeleteSecret_Call{Call: _e.mock.On("DeleteSecret", id, userID)}
}

func (_c *MockSecretRepository_DeleteSecret_Call) Run(run func(id string, userID string)) *MockSecretRepository_DeleteSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockSecretRepository_DeleteSecret_Call) Return(_a0 error) *MockSecretRepository_DeleteSecret_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSecretRepository_DeleteSecret_Call) RunAndReturn(run func(string, string) error) *MockSecretRepository_DeleteSecret_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecret provides a mock function with given fields: id, userID
func (_m *MockSecretRepository) GetSecret(id string, userID string) (*postgres.Secret, error) {
	ret := _m.Called(id, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetSecret")
	}

	var r0 *postgres.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*postgres.Secret, error)); ok {
		return rf(id, userID)
	}
	if rf, ok := ret.Get(0).(func(string, string) *postgres.Secret); ok {
		r0 = rf(id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*postgres.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(id, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretRepository_GetSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecret'
type MockSecretRepository_GetSecret_Call struct {
	*mock.Call
}

// GetSecret is a helper method to define mock.On call
//   - id string
//   - userID string
func (_e *MockSecretRepository_Expecter) GetSecret(id interface{}, userID interface{}) *MockSecretRepository_GetSecret_Call {
	return &MockSecretRepository_GetSecret_Call{Call: _e.mock.On("GetSecret", id, userID)}
}

func (_c *MockSecretRepository_GetSecret_Call) Run(run func(id string, userID string)) *MockSecretRepository_GetSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockSecretRepository_GetSecret_Call) Return(_a0 *postgres.Secret, _a1 error) *MockSecretRepository_GetSecret_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretRepository_GetSecret_Call) RunAndReturn(run func(string, string) (*postgres.Secret, error)) *MockSecretRepository_GetSecret_Call {
	_c.Call.Return(run)
	return _c
}

// ListSecretsByUser provides a mock function with given fields: userID
func (_m *MockSecretRepository) ListSecretsByUser(userID string) ([]*postgres.Secret, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for ListSecretsByUser")
	}

	var r0 []*postgres.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*postgres.Secret, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) []*postgres.Secret); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*postgres.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretRepository_ListSecretsByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSecretsByUser'
type MockSecretRepository_ListSecretsByUser_Call struct {
	*mock.Call
}

// ListSecretsByUser is a helper method to define mock.On call
//   - userID string
func (_e *MockSecretRepository_Expecter) ListSecretsByUser(userID interface{}) *MockSecretRepository_ListSecretsByUser_Call {
	return &MockSecretRepository_ListSecretsByUser_Call{Call: _e.mock.On("ListSecretsByUser", userID)}
}

func (_c *MockSecretRepository_ListSecretsByUser_Call) Run(run func(userID string)) *MockSecretRepository_ListSecretsByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockSecretRepository_ListSecretsByUser_Call) Return(_a0 []*postgres.Secret, _a1 error) *MockSecretRepository_ListSecretsByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretRepository_ListSecretsByUser_Call) RunAndReturn(run func(string) ([]*postgres.Secret, error)) *MockSecretRepository_ListSecretsByUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBinarySecret provides a mock function with given fields: id, userID, storageKey, fileSize, version
func (_m *MockSecretRepository) UpdateBinarySecret(id string, userID string, storageKey string, fileSize int64, version int32) error {
	ret := _m.Called(id, userID, storageKey, fileSize, version)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBinarySecret")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, int64, int32) error); ok {
		r0 = rf(id, userID, storageKey, fileSize, version)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSecretRepository_UpdateBinarySecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBinarySecret'
type MockSecretRepository_UpdateBinarySecret_Call struct {
	*mock.Call
}

// UpdateBinarySecret is a helper method to define mock.On call
//   - id string
//   - userID string
//   - storageKey string
//   - fileSize int64
//   - version int32
func (_e *MockSecretRepository_Expecter) UpdateBinarySecret(id interface{}, userID interface{}, storageKey interface{}, fileSize interface{}, version interface{}) *MockSecretRepository_UpdateBinarySecret_Call {
	return &MockSecretRepository_UpdateBinarySecret_Call{Call: _e.mock.On("UpdateBinarySecret", id, userID, storageKey, fileSize, version)}
}

func (_c *MockSecretRepository_UpdateBinarySecret_Call) Run(run func(id string, userID string, storageKey string, fileSize int64, version int32)) *MockSecretRepository_UpdateBinarySecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string), args[3].(int64), args[4].(int32))
	})
	return _c
}

func (_c *MockSecretRepository_UpdateBinarySecret_Call) Return(_a0 error) *MockSecretRepository_UpdateBinarySecret_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSecretRepository_UpdateBinarySecret_Call) RunAndReturn(run func(string, string, string, int64, int32) error) *MockSecretRepository_UpdateBinarySecret_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSecret provides a mock function with given fields: s
func (_m *MockSecretRepository) UpdateSecret(s *postgres.Secret) (*postgres.Secret, error) {
	ret := _m.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSecret")
	}

	var r0 *postgres.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(*postgres.Secret) (*postgres.Secret, error)); ok {
		return rf(s)
	}
	if rf, ok := ret.Get(0).(func(*postgres.Secret) *postgres.Secret); ok {
		r0 = rf(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*postgres.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(*postgres.Secret) error); ok {
		r1 = rf(s)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretRepository_UpdateSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSecret'
type MockSecretRepository_UpdateSecret_Call struct {
	*mock.Call
}

// UpdateSecret is a helper method to define mock.On call
//   - s *postgres.Secret
func (_e *MockSecretRepository_Expecter) UpdateSecret(s interface{}) *MockSecretRepository_UpdateSecret_Call {
	return &MockSecretRepository_UpdateSecret_Call{Call: _e.mock.On("UpdateSecret", s)}
}

func (_c *MockSecretRepository_UpdateSecret_Call) Run(run func(s *postgres.Secret)) *MockSecretRepository_UpdateSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*postgres.Secret))
	})
	return _c
}

func (_c *MockSecretRepository_UpdateSecret_Call) Return(_a0 *postgres.Secret, _a1 error) *MockSecretRepository_UpdateSecret_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretRepository_UpdateSecret_Call) RunAndReturn(run func(*postgres.Secret) (*postgres.Secret, error)) *MockSecretRepository_UpdateSecret_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSecretRepository creates a new instance of MockSecretRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSecretRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSecretRepository {
	mock := &MockSecretRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
