// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: gophkeeper/v1/secret.proto

package gophkeeperv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SecretType enumerates the supported secret kinds.
type SecretType int32

const (
	SecretType_SECRET_TYPE_UNSPECIFIED SecretType = 0
	SecretType_SECRET_TYPE_CREDENTIAL  SecretType = 1
	SecretType_SECRET_TYPE_TEXT        SecretType = 2
	SecretType_SECRET_TYPE_BINARY      SecretType = 3
	SecretType_SECRET_TYPE_CARD        SecretType = 4
)

// Enum value maps for SecretType.
var (
	SecretType_name = map[int32]string{
		0: "SECRET_TYPE_UNSPECIFIED",
		1: "SECRET_TYPE_CREDENTIAL",
		2: "SECRET_TYPE_TEXT",
		3: "SECRET_TYPE_BINARY",
		4: "SECRET_TYPE_CARD",
	}
	SecretType_value = map[string]int32{
		"SECRET_TYPE_UNSPECIFIED": 0,
		"SECRET_TYPE_CREDENTIAL":  1,
		"SECRET_TYPE_TEXT":        2,
		"SECRET_TYPE_BINARY":      3,
		"SECRET_TYPE_CARD":        4,
	}
)

func (x SecretType) Enum() *SecretType {
	p := new(SecretType)
	*p = x
	return p
}

func (x SecretType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecretType) Descriptor() protoreflect.EnumDescriptor {
	return file_gophkeeper_v1_secret_proto_enumTypes[0].Descriptor()
}

func (SecretType) Type() protoreflect.EnumType {
	return &file_gophkeeper_v1_secret_proto_enumTypes[0]
}

func (x SecretType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SecretType.Descriptor instead.
func (SecretType) EnumDescriptor() ([]byte, []int) {
	return file_gophkeeper_v1_secret_proto_rawDescGZIP(), []int{0}
}

// SecretMeta holds the metadata shown in list views.
type SecretMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type  SecretType             `protobuf:"varint,3,opt,name=type,proto3,enum=gophkeeper.v1.SecretType" json:"type,omitempty"`
	// metadata is a JSON-encoded map of arbitrary user-defined tags.
	Metadata      string                 `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	FileSize      int64                  `protobuf:"varint,5,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	Version       int32                  `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretMeta) Reset() {
	*x = SecretMeta{}
	mi := &file_gophkeeper_v1_secret_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretMeta) ProtoMessage() {}

func (x *SecretMeta) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_secret_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretMeta.ProtoReflect.Descriptor instead.
func (*SecretMeta) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_secret_proto_rawDescGZIP(), []int{0}
}

func (x *SecretMeta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SecretMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SecretMeta) GetType() SecretType {
	if x != nil {
		return x.Type
	}
	return SecretType_SECRET_TYPE_UNSPECIFIED
}

func (x *SecretMeta) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *SecretMeta) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *SecretMeta) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SecretMeta) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SecretMeta) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListSecretsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsRequest) Reset() {
	*x = ListSecretsRequest{}
	mi := &file_gophkeeper_v1_secret_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsRequest) ProtoMessage() {}

func (x *ListSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_secret_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsRequest.ProtoReflect.Descriptor instead.
func (*ListSecretsRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_secret_proto_rawDescGZIP(), []int{1}
}

type ListSecretsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secrets       []*SecretMeta          `protobuf:"bytes,1,rep,name=secrets,proto3" json:"secrets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsResponse) Reset() {
	*x = ListSecretsResponse{}
	mi := &file_gophkeeper_v1_secret_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsResponse) ProtoMessage() {}

func (x *ListSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_secret_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsResponse.ProtoReflect.Descriptor instead.
func (*ListSecretsResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_secret_proto_rawDescGZIP(), []int{2}
}

func (x *ListSecretsResponse) GetSecrets() []*SecretMeta {
	if x != nil {
		return x.Secrets
	}
	return nil
}

type GetSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretRequest) Reset() {
	*x = GetSecretRequest{}
	mi := &file_gophkeeper_v1_secret_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretRequest) ProtoMessage() {}

func (x *GetSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_secret_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretRequest.ProtoReflect.Descriptor instead.
func (*GetSecretRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_secret_proto_rawDescGZIP(), []int{3}
}

func (x *GetSecretRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetSecretResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Meta  *SecretMeta            `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// payload is the decrypted secret content as JSON bytes.
	Payload       []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretResponse) Reset() {
	*x = GetSecretResponse{}
	mi := &file_gophkeeper_v1_secret_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretResponse) ProtoMessage() {}

func (x *GetSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_secret_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretResponse.ProtoReflect.Descriptor instead.
func (*GetSecretResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_secret_proto_rawDescGZIP(), []int{4}
}

func (x *GetSecretResponse) GetMeta() *SecretMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetSecretResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type CreateSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          SecretType             `protobuf:"varint,2,opt,name=type,proto3,enum=gophkeeper.v1.SecretType" json:"type,omitempty"`
	Metadata      string                 `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSecretRequest) Reset() {
	*x = CreateSecretRequest{}
	mi := &file_gophkeeper_v1_secret_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretRequest) ProtoMessage() {}

func (x *CreateSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_secret_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSecretRequest.ProtoReflect.Descriptor instead.
func (*CreateSecretRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_secret_proto_rawDescGZIP(), []int{5}
}

func (x *CreateSecretRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSecretRequest) GetType() SecretType {
	if x != nil {
		return x.Type
	}
	return SecretType_SECRET_TYPE_UNSPECIFIED
}

func (x *CreateSecretRequest) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *CreateSecretRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type CreateSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *SecretMeta            `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSecretResponse) Reset() {
	*x = CreateSecretResponse{}
	mi := &file_gophkeeper_v1_secret_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretResponse) ProtoMessage() {}

func (x *CreateSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_secret_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSecretResponse.ProtoReflect.Descriptor instead.
func (*CreateSecretResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_secret_proto_rawDescGZIP(), []int{6}
}

func (x *CreateSecretResponse) GetMeta() *SecretMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type UpdateSecretRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Metadata string                 `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Payload  []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	// version must match the current server version to prevent conflicts.
	Version       int32 `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSecretRequest) Reset() {
	*x = UpdateSecretRequest{}
	mi := &file_gophkeeper_v1_secret_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSecretRequest) ProtoMessage() {}

func (x *UpdateSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_secret_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSecretRequest.ProtoReflect.Descriptor instead.
func (*UpdateSecretRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_secret_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateSecretRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSecretRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateSecretRequest) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *UpdateSecretRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UpdateSecretRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type UpdateSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *SecretMeta            `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSecretResponse) Reset() {
	*x = UpdateSecretResponse{}
	mi := &file_gophkeeper_v1_secret_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSecretResponse) ProtoMessage() {}

func (x *UpdateSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_secret_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSecretResponse.ProtoReflect.Descriptor instead.
func (*UpdateSecretResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_secret_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateSecretResponse) GetMeta() *SecretMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type DeleteSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretRequest) Reset() {
	*x = DeleteSecretRequest{}
	mi := &file_gophkeeper_v1_secret_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretRequest) ProtoMessage() {}

func (x *DeleteSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_secret_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretRequest.ProtoReflect.Descriptor instead.
func (*DeleteSecretRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_secret_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteSecretRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretResponse) Reset() {
	*x = DeleteSecretResponse{}
	mi := &file_gophkeeper_v1_secret_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretResponse) ProtoMessage() {}

func (x *DeleteSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_secret_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretResponse.ProtoReflect.Descriptor instead.
func (*DeleteSecretResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_secret_proto_rawDescGZIP(), []int{10}
}

// UploadFileRequest is sent in a stream. The first message carries the header;
// subsequent messages carry raw file chunks.
type UploadFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*UploadFileRequest_Header
	//	*UploadFileRequest_Chunk
	Data          isUploadFileRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_gophkeeper_v1_secret_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_secret_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequest.ProtoReflect.Descriptor instead.
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_secret_proto_rawDescGZIP(), []int{11}
}

func (x *UploadFileRequest) GetData() isUploadFileRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadFileRequest) GetHeader() *UploadHeader {
	if x != nil {
		if x, ok := x.Data.(*UploadFileRequest_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *UploadFileRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Data.(*UploadFileRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isUploadFileRequest_Data interface {
	isUploadFileRequest_Data()
}

type UploadFileRequest_Header struct {
	Header *UploadHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type UploadFileRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*UploadFileRequest_Header) isUploadFileRequest_Data() {}

func (*UploadFileRequest_Chunk) isUploadFileRequest_Data() {}

type UploadHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Metadata      string                 `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadHeader) Reset() {
	*x = UploadHeader{}
	mi := &file_gophkeeper_v1_secret_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadHeader) ProtoMessage() {}

func (x *UploadHeader) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_secret_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadHeader.ProtoReflect.Descriptor instead.
func (*UploadHeader) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_secret_proto_rawDescGZIP(), []int{12}
}

func (x *UploadHeader) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UploadHeader) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type UploadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *SecretMeta            `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileResponse) Reset() {
	*x = UploadFileResponse{}
	mi := &file_gophkeeper_v1_secret_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResponse) ProtoMessage() {}

func (x *UploadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_secret_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileResponse.ProtoReflect.Descriptor instead.
func (*UploadFileResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_secret_proto_rawDescGZIP(), []int{13}
}

func (x *UploadFileResponse) GetMeta() *SecretMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type DownloadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileRequest) Reset() {
	*x = DownloadFileRequest{}
	mi := &file_gophkeeper_v1_secret_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileRequest) ProtoMessage() {}

func (x *DownloadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_secret_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileRequest.ProtoReflect.Descriptor instead.
func (*DownloadFileRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_secret_proto_rawDescGZIP(), []int{14}
}

func (x *DownloadFileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DownloadFileResponse is sent in a stream. The first message carries the
// header; subsequent messages carry raw file chunks.
type DownloadFileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*DownloadFileResponse_Meta
	//	*DownloadFileResponse_Chunk
	Data          isDownloadFileResponse_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileResponse) Reset() {
	*x = DownloadFileResponse{}
	mi := &file_gophkeeper_v1_secret_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileResponse) ProtoMessage() {}

func (x *DownloadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_secret_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileResponse.ProtoReflect.Descriptor instead.
func (*DownloadFileResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_secret_proto_rawDescGZIP(), []int{15}
}

func (x *DownloadFileResponse) GetData() isDownloadFileResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DownloadFileResponse) GetMeta() *SecretMeta {
	if x != nil {
		if x, ok := x.Data.(*DownloadFileResponse_Meta); ok {
			return x.Meta
		}
	}
	return nil
}

func (x *DownloadFileResponse) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Data.(*DownloadFileResponse_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isDownloadFileResponse_Data interface {
	isDownloadFileResponse_Data()
}

type DownloadFileResponse_Meta struct {
	Meta *SecretMeta `protobuf:"bytes,1,opt,name=meta,proto3,oneof"`
}

type DownloadFileResponse_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*DownloadFileResponse_Meta) isDownloadFileResponse_Data() {}

func (*DownloadFileResponse_Chunk) isDownloadFileResponse_Data() {}

var File_gophkeeper_v1_secret_proto protoreflect.FileDescriptor

const file_gophkeeper_v1_secret_proto_rawDesc = "" +
	"\n" +
	"\x1agophkeeper/v1/secret.proto\x12\rgophkeeper.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa8\x02\n" +
	"\n" +
	"SecretMeta\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12-\n" +
	"\x04type\x18\x03 \x01(\x0e2\x19.gophkeeper.v1.SecretTypeR\x04type\x12\x1a\n" +
	"\bmetadata\x18\x04 \x01(\tR\bmetadata\x12\x1b\n" +
	"\tfile_size\x18\x05 \x01(\x03R\bfileSize\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x05R\aversion\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x14\n" +
	"\x12ListSecretsRequest\"J\n" +
	"\x13ListSecretsResponse\x123\n" +
	"\asecrets\x18\x01 \x03(\v2\x19.gophkeeper.v1.SecretMetaR\asecrets\"\"\n" +
	"\x10GetSecretRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\\\n" +
	"\x11GetSecretResponse\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.gophkeeper.v1.SecretMetaR\x04meta\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"\x8e\x01\n" +
	"\x13CreateSecretRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12-\n" +
	"\x04type\x18\x02 \x01(\x0e2\x19.gophkeeper.v1.SecretTypeR\x04type\x12\x1a\n" +
	"\bmetadata\x18\x03 \x01(\tR\bmetadata\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"E\n" +
	"\x14CreateSecretResponse\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.gophkeeper.v1.SecretMetaR\x04meta\"\x89\x01\n" +
	"\x13UpdateSecretRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bmetadata\x18\x03 \x01(\tR\bmetadata\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x05R\aversion\"E\n" +
	"\x14UpdateSecretResponse\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.gophkeeper.v1.SecretMetaR\x04meta\"%\n" +
	"\x13DeleteSecretRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x16\n" +
	"\x14DeleteSecretResponse\"j\n" +
	"\x11UploadFileRequest\x125\n" +
	"\x06header\x18\x01 \x01(\v2\x1b.gophkeeper.v1.UploadHeaderH\x00R\x06header\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\x06\n" +
	"\x04data\">\n" +
	"\fUploadHeader\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bmetadata\x18\x03 \x01(\tR\bmetadata\"C\n" +
	"\x12UploadFileResponse\x12-\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.gophkeeper.v1.SecretMetaR\x04meta\"%\n" +
	"\x13DownloadFileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"g\n" +
	"\x14DownloadFileResponse\x12/\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.gophkeeper.v1.SecretMetaH\x00R\x04meta\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\x06\n" +
	"\x04data*\x89\x01\n" +
	"\n" +
	"SecretType\x12\x1b\n" +
	"\x17SECRET_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16SECRET_TYPE_CREDENTIAL\x10\x01\x12\x14\n" +
	"\x10SECRET_TYPE_TEXT\x10\x02\x12\x16\n" +
	"\x12SECRET_TYPE_BINARY\x10\x03\x12\x14\n" +
	"\x10SECRET_TYPE_CARD\x10\x042\xf0\x04\n" +
	"\rSecretService\x12T\n" +
	"\vListSecrets\x12!.gophkeeper.v1.ListSecretsRequest\x1a\".gophkeeper.v1.ListSecretsResponse\x12N\n" +
	"\tGetSecret\x12\x1f.gophkeeper.v1.GetSecretRequest\x1a .gophkeeper.v1.GetSecretResponse\x12W\n" +
	"\fCreateSecret\x12\".gophkeeper.v1.CreateSecretRequest\x1a#.gophkeeper.v1.CreateSecretResponse\x12W\n" +
	"\fUpdateSecret\x12\".gophkeeper.v1.UpdateSecretRequest\x1a#.gophkeeper.v1.UpdateSecretResponse\x12W\n" +
	"\fDeleteSecret\x12\".gophkeeper.v1.DeleteSecretRequest\x1a#.gophkeeper.v1.DeleteSecretResponse\x12S\n" +
	"\n" +
	"UploadFile\x12 .gophkeeper.v1.UploadFileRequest\x1a!.gophkeeper.v1.UploadFileResponse(\x01\x12Y\n" +
	"\fDownloadFile\x12\".gophkeeper.v1.DownloadFileRequest\x1a#.gophkeeper.v1.DownloadFileResponse0\x01B@Z>github.com/arsykor/gophkeeper/proto/gophkeeper/v1;gophkeeperv1b\x06proto3"

var (
	file_gophkeeper_v1_secret_proto_rawDescOnce sync.Once
	file_gophkeeper_v1_secret_proto_rawDescData []byte
)

func file_gophkeeper_v1_secret_proto_rawDescGZIP() []byte {
	file_gophkeeper_v1_secret_proto_rawDescOnce.Do(func() {
		file_gophkeeper_v1_secret_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gophkeeper_v1_secret_proto_rawDesc), len(file_gophkeeper_v1_secret_proto_rawDesc)))
	})
	return file_gophkeeper_v1_secret_proto_rawDescData
}

var file_gophkeeper_v1_secret_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gophkeeper_v1_secret_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_gophkeeper_v1_secret_proto_goTypes = []any{
	(SecretType)(0),               // 0: gophkeeper.v1.SecretType
	(*SecretMeta)(nil),            // 1: gophkeeper.v1.SecretMeta
	(*ListSecretsRequest)(nil),    // 2: gophkeeper.v1.ListSecretsRequest
	(*ListSecretsResponse)(nil),   // 3: gophkeeper.v1.ListSecretsResponse
	(*GetSecretRequest)(nil),      // 4: gophkeeper.v1.GetSecretRequest
	(*GetSecretResponse)(nil),     // 5: gophkeeper.v1.GetSecretResponse
	(*CreateSecretRequest)(nil),   // 6: gophkeeper.v1.CreateSecretRequest
	(*CreateSecretResponse)(nil),  // 7: gophkeeper.v1.CreateSecretResponse
	(*UpdateSecretRequest)(nil),   // 8: gophkeeper.v1.UpdateSecretRequest
	(*UpdateSecretResponse)(nil),  // 9: gophkeeper.v1.UpdateSecretResponse
	(*DeleteSecretRequest)(nil),   // 10: gophkeeper.v1.DeleteSecretRequest
	(*DeleteSecretResponse)(nil),  // 11: gophkeeper.v1.DeleteSecretResponse
	(*UploadFileRequest)(nil),     // 12: gophkeeper.v1.UploadFileRequest
	(*UploadHeader)(nil),          // 13: gophkeeper.v1.UploadHeader
	(*UploadFileResponse)(nil),    // 14: gophkeeper.v1.UploadFileResponse
	(*DownloadFileRequest)(nil),   // 15: gophkeeper.v1.DownloadFileRequest
	(*DownloadFileResponse)(nil),  // 16: gophkeeper.v1.DownloadFileResponse
	(*timestamppb.Timestamp)(nil), // 17: google.protobuf.Timestamp
}
var file_gophkeeper_v1_secret_proto_depIdxs = []int32{
	0,  // 0: gophkeeper.v1.SecretMeta.type:type_name -> gophkeeper.v1.SecretType
	17, // 1: gophkeeper.v1.SecretMeta.created_at:type_name -> google.protobuf.Timestamp
	17, // 2: gophkeeper.v1.SecretMeta.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 3: gophkeeper.v1.ListSecretsResponse.secrets:type_name -> gophkeeper.v1.SecretMeta
	1,  // 4: gophkeeper.v1.GetSecretResponse.meta:type_name -> gophkeeper.v1.SecretMeta
	0,  // 5: gophkeeper.v1.CreateSecretRequest.type:type_name -> gophkeeper.v1.SecretType
	1,  // 6: gophkeeper.v1.CreateSecretResponse.meta:type_name -> gophkeeper.v1.SecretMeta
	1,  // 7: gophkeeper.v1.UpdateSecretResponse.meta:type_name -> gophkeeper.v1.SecretMeta
	13, // 8: gophkeeper.v1.UploadFileRequest.header:type_name -> gophkeeper.v1.UploadHeader
	1,  // 9: gophkeeper.v1.UploadFileResponse.meta:type_name -> gophkeeper.v1.SecretMeta
	1,  // 10: gophkeeper.v1.DownloadFileResponse.meta:type_name -> gophkeeper.v1.SecretMeta
	2,  // 11: gophkeeper.v1.SecretService.ListSecrets:input_type -> gophkeeper.v1.ListSecretsRequest
	4,  // 12: gophkeeper.v1.SecretService.GetSecret:input_type -> gophkeeper.v1.GetSecretRequest
	6,  // 13: gophkeeper.v1.SecretService.CreateSecret:input_type -> gophkeeper.v1.CreateSecretRequest
	8,  // 14: gophkeeper.v1.SecretService.UpdateSecret:input_type -> gophkeeper.v1.UpdateSecretRequest
	10, // 15: gophkeeper.v1.SecretService.DeleteSecret:input_type -> gophkeeper.v1.DeleteSecretRequest
	12, // 16: gophkeeper.v1.SecretService.UploadFile:input_type -> gophkeeper.v1.UploadFileRequest
	15, // 17: gophkeeper.v1.SecretService.DownloadFile:input_type -> gophkeeper.v1.DownloadFileRequest
	3,  // 18: gophkeeper.v1.SecretService.ListSecrets:output_type -> gophkeeper.v1.ListSecretsResponse
	5,  // 19: gophkeeper.v1.SecretService.GetSecret:output_type -> gophkeeper.v1.GetSecretResponse
	7,  // 20: gophkeeper.v1.SecretService.CreateSecret:output_type -> gophkeeper.v1.CreateSecretResponse
	9,  // 21: gophkeeper.v1.SecretService.UpdateSecret:output_type -> gophkeeper.v1.UpdateSecretResponse
	11, // 22: gophkeeper.v1.SecretService.DeleteSecret:output_type -> gophkeeper.v1.DeleteSecretResponse
	14, // 23: gophkeeper.v1.SecretService.UploadFile:output_type -> gophkeeper.v1.UploadFileResponse
	16, // 24: gophkeeper.v1.SecretService.DownloadFile:output_type -> gophkeeper.v1.DownloadFileResponse
	18, // [18:25] is the sub-list for method output_type
	11, // [11:18] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_gophkeeper_v1_secret_proto_init() }
func file_gophkeeper_v1_secret_proto_init() {
	if File_gophkeeper_v1_secret_proto != nil {
		return
	}
	file_gophkeeper_v1_secret_proto_msgTypes[11].OneofWrappers = []any{
		(*UploadFileRequest_Header)(nil),
		(*UploadFileRequest_Chunk)(nil),
	}
	file_gophkeeper_v1_secret_proto_msgTypes[15].OneofWrappers = []any{
		(*DownloadFileResponse_Meta)(nil),
		(*DownloadFileResponse_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gophkeeper_v1_secret_proto_rawDesc), len(file_gophkeeper_v1_secret_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gophkeeper_v1_secret_proto_goTypes,
		DependencyIndexes: file_gophkeeper_v1_secret_proto_depIdxs,
		EnumInfos:         file_gophkeeper_v1_secret_proto_enumTypes,
		MessageInfos:      file_gophkeeper_v1_secret_proto_msgTypes,
	}.Build()
	File_gophkeeper_v1_secret_proto = out.File
	file_gophkeeper_v1_secret_proto_goTypes = nil
	file_gophkeeper_v1_secret_proto_depIdxs = nil
}
